name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.9, 3.11]


    runs-on: ubuntu-latest

    steps:
          
      - name: checkout
        uses: actions/checkout@v4


      - name: use reusable setup
        uses: ./.github/workflows/reusable-setup.yml
        with: 
          python-version: ${{ matrix.python-version }}    

  test:
        needs: build
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: [3.9, 3.11]

        steps:

        #  - name: checkout
        #    uses: actions/checkout@v4

          - name: use reusable setup
            uses: ./.github/workflows/reusable-setup.yml
            with: 
              python-version: ${{ matrix.python-version }}

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install flake8 pytest

          - name: Run flake8 
            run: flake8 --count --select=E901,E999,F821,F822,F823 --show-source --statistics

          - name: Run tests
            run: pytest    