name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.9, 3.11]


    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upload project code
        uses: actions/upload-artifact@v4
        with: 
          name: project_code_real
          path: .

          

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:

     ## - uses: actions/checkout@v4

      - name: download
        uses: actions/download-artifact@v4
        with:
          name: project_code_real
          path: .
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Run flake8
        run: flake8 --count --select=E901,E999,F821,F822,F823 --show-source --statistics

      - name: Run tests
        run: pytest