name: reusable-setup

on:
  workflow_call:
    inputs:

      python-version: #Input-ID
        description: "Version of Python"
        required: true
        type: string



jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    
        - name: setup language
          uses: actions/setup-python@v4
          with:
            python-version: ${{ inputs.python-version }}
            cache: pip